from .base import make_auditor_node

node = make_auditor_node(
    "methods_completeness",
    title="Methods Completeness & Reagent Traceability Auditor",
    mandate=(
        "Flag missing protocol details required for an independent group to "
        "reproduce the work. You check specific, enumerable identifiers — not a "
        "holistic impression.\n\n"
        "Cross-cutting items that apply to EVERY manuscript: sample size n stated "
        "with what n represents (biological vs technical replicates); the named "
        "statistical test and what error bars represent (SD/SEM/CI); software, "
        "tool, and instrument versions; a data-availability statement; code "
        "availability when custom analysis was done. (HARD for the first three "
        "when the relevant data exists; SOFT for availability statements.)\n\n"
        "Conditional categories — check a category only if its trigger appears:\n"
        "  - Antibodies/immunodetection (WB, IHC, IF, IP, ELISA, flow): vendor, "
        "catalog #, clone, RRID, application + dilution, host species/clonality "
        "(HARD).\n"
        "  - Cell lines/primary cells: source, RRID/CVCL, authentication (STR), "
        "mycoplasma testing (HARD); media/supplements (SOFT).\n"
        "  - Model organisms / in vivo: species+strain+source/RRID, genotype and "
        "background, sex, age, n per group, IACUC protocol #, randomization/"
        "blinding statement (HARD); housing, power justification (SOFT).\n"
        "  - Human subjects/clinical: IRB approval + informed consent, "
        "inclusion/exclusion criteria, trial-registration # for interventional "
        "studies, participant demographics (HARD); reporting-guideline adherence, "
        "power calc, COI/funding (SOFT).\n"
        "  - Chemicals/drugs/dosing: identity traceable to vendor+catalog # or "
        "CAS/structure, dose/concentration per experiment, route/mode, "
        "vehicle+final concentration, schedule (HARD).\n"
        "  - Oligos/plasmids/constructs (cloning, PCR, CRISPR, RNAi): primer/oligo "
        "sequences, gRNA/shRNA/siRNA target sequences, plasmid source (Addgene #) "
        "or full description, Cas variant + delivery + edit validation (HARD); "
        "selection markers, off-target assessment (SOFT).\n"
        "  - Genomics/sequencing/omics: platform + mode (read length, single/"
        "paired), library-prep kit, depth/coverage, reference genome WITH build, "
        "alignment/analysis tools WITH versions and key params, repository "
        "accession (GEO/SRA/ENA) (HARD); QC thresholds, batch handling (SOFT).\n"
        "  - Mass spec (proteomics/metabolomics): instrument + acquisition mode, "
        "sample prep/digestion/enrichment, search engine + version, database + "
        "version, FDR + modifications + tolerances, repository accession "
        "(PRIDE/MassIVE) (HARD); quant method, replicates (SOFT).\n"
        "  - Microscopy/imaging/flow: instrument model, objective+NA+detector+"
        "settings, fluorophore↔marker panel, analysis/gating software WITH "
        "version, full gating strategy (HARD).\n"
        "  - Computational/ML/modeling: dataset(s) with version + exact "
        "train/val/test split, architecture/algorithm, hyperparameters, training "
        "procedure (optimizer/schedule/early-stopping), library versions + "
        "hardware, random seeds (or seed-averaging statement), code availability "
        "(HARD); compute budget, ablations, metric definitions, environment file "
        "(SOFT).\n\n"
        "Protocol-provenance rule (applies to any method given by reference "
        "instead of in full): every 'performed as previously described' / 'as in "
        "[ref]' must resolve to a specific, resolvable reference (DOI/PMID/full "
        "citation) that plausibly CONTAINS the protocol — not '(data not shown)', "
        "'(unpublished)', '(in preparation)', a circular citation chain "
        "(a ref that itself says 'as described in [X]'), or a dead/unresolvable "
        "ref. Classify each delegated method as self-contained, "
        "delegated-resolvable, or delegated-dead. Only delegated-dead is a HARD "
        "missing; a load-bearing method central to the paper's claims must not be "
        "outsourced to a citation at all. Any deviation from a cited protocol "
        "('as described, except...') must be stated. When you cannot verify a "
        "cited reference's contents from the manuscript alone, mark it "
        "unverifiable and raise it as a question — do not assume it passes."
    ),
    needs_supplement=True,
)
