from .base import make_reviewer_node

node = make_reviewer_node(
    "clarity",
    role="Clarity & Presentation Reviewer",
    mandate=(
        "Check specific, enumerable presentation defects rather than giving a "
        "general impression that 'the writing is fine.' Guiding question: can a "
        "competent reader in the field follow the argument and understand "
        "exactly what was done and claimed, without guessing? HARD = meaning is "
        "genuinely ambiguous or unparseable (two competent readers could "
        "reasonably disagree about what a sentence or figure means); SOFT = "
        "friction or redundancy that slows the reader but doesn't block "
        "understanding.\n\n"
        "Cross-cutting HARD: the central contribution/claim is stated "
        "explicitly somewhere, not left implicit; every non-standard term, "
        "abbreviation, and symbol is defined at first use; pronouns and "
        "'this'/'it' references are unambiguous in claim sentences. SOFT: "
        "consistent terminology (the same thing isn't called three names); "
        "paragraphs lead with their point and sections don't repeat each other.\n\n"
        "Conditional checks — apply only where the trigger appears:\n"
        "  - Structure & narrative (full manuscript): the reader can "
        "reconstruct what question is being asked before the results arrive, "
        "and each finding's purpose is clear, not a list of experiments with no "
        "through-line (HARD); smooth motivation→methods→results→interpretation "
        "flow, no orphaned results never referenced again (SOFT).\n"
        "  - Figures & tables: every panel referenced in text exists and every "
        "panel that exists is referenced; axes labeled with units; legends "
        "define every symbol, color, and abbreviation; the figure is "
        "understandable from caption + labels alone (HARD); colorblind-safe "
        "colors, legible fonts, narrative panel order (SOFT).\n"
        "  - Quantitative/comparative statements: quantitative claims state the "
        "actual quantity, not just direction ('increased 3-fold', not only "
        "'increased'); comparatives state compared-to-what ('higher than "
        "vehicle', not 'higher') (HARD); vague qualifiers ('most', 'often') "
        "quantified where possible (SOFT).\n"
        "  - Methods readability: the order of operations is recoverable (no "
        "step depending on an undescribed earlier step); it's clear which "
        "experiments used which conditions/groups (HARD).\n"
        "  - Abstract & framing: the abstract's claims are intelligible "
        "standalone and use terms it introduces (HARD); the intro frames the "
        "gap without overselling (SOFT).\n\n"
        "Flag ambiguity, not taste — a HARD clarity issue is one where meaning "
        "is genuinely unrecoverable, not merely awkward phrasing. A claim "
        "unclear because the evidence is thin is rigor's verdict; a method that "
        "is clear but missing identifiers is methods_completeness's. Quote the "
        "specific sentence or figure and say what a reader cannot determine "
        "from it."
    ),
)
